language: cpp
compiler: gcc
dist: trusty
sudo: required

before_install:
    - sudo apt-get update -qq
    - wget https://www.libsdl.org/release/SDL2-2.0.8.tar.gz && tar -xzf SDL2-2.0.8.tar.gz
    - pushd SDL2-2.0.8 && ./configure && make && sudo make install && popd
    - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.3.tar.gz && tar -xzf SDL2_image-2.0.3.tar.gz
    - pushd SDL2_image-2.0.3 && ./configure && make && sudo make install && popd
    - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz && tar -xzf SDL2_ttf-2.0.14.tar.gz
    - pushd SDL2_ttf-2.0.14 && ./configure && make && sudo make install && popd 
    - wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz && tar -xzf SDL2_net-2.0.1.tar.gz
    - pushd SDL2_net-2.0.1 && ./configure && make && sudo make install && popd
    - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.tar.gz && tar -xzf SDL2_mixer-2.0.2.tar.gz
    - pushd SDL2_mixer-2.0.2 && ./configure && make && sudo make install && popd
    - sudo apt-get install -qq libsqlite3-dev libtinyxml2-dev

install:
    - wget http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.3.tar.gz
    - tar -xzf SDL2_gfx-1.0.3.tar.gz
    - pushd SDL2_gfx-1.0.3 && ./configure && make && sudo make install && popd
    - pushd guisan && scons && sudo scons install && popd

script: ./configure && make
